sudo: required
services:
  - docker
before_install:
  - docker pull node:9.11.2-slim
  - echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

script:
  - docker build -t cjy632258/prerender .

after_success:
  - docker push cjy632258/prerender